### PR TITLE
Fix demo startup race condition

### PR DESCRIPTION
**Pull request by johnpmayer**
While the backoff function does add a modicum of extra complexity, it does eliminate a "PONG flood" once the server does begin to respond, breaking the actual "rally-like" behavior where the client waits for a pong before deciding to ping. 

Could be tightened further by using a new message (READY/GO), but I like re-using the PING message because it keeps the protocol simple on the server. 

Some things to cleanup

- [x] Implement the same logic for the wasm_bindgen example (factor?)
- [x] Clean up hard-coded server IPs (or at least revert the change)

### CODE REVIEW

**Comment by naia-rs** [comment]
Great idea here man :+1:
Thank you!

**Comment by johnpmayer** [comment]
Ok I think this is ready for a review, I'm happy where it landed. 

Some observations (non-goals for this PR)

- miniquad and wasm_bindgen "app.rs" are identical, modulo the one line which is importing logging. Might be possible to clean that up (with a feature flag, consolidate the two client demo codebases?)
- Very tangential: miniquad feels like a worse stdweb, in terms of architecture and build tooling. It doesn't feel nearly as tight as wasm-pack. And the deployment story for naia-socket.js seems underdeveloped. As an end user right now, I'll probably only be using the wasm-bindgen impementation. Maybe i'm missing something about the appeal of miniquad, I'm not plugged into it as a platform/community.

**Review by naia-rs — APPROVED** [review]
Awesome man, yeah I agree about allowing the end user to determine their own IP address instead of trying to detect it automatically :+1: (especially since that 'find_my_ip_address' helper function only works if you have a public IP)

**Comment by naia-rs** [comment]
Hey John, thanks for taking a look at this over the weekend! I really appreciate the help here, as well as the help I got from looking at your `quicksilver-utils` a couple months ago, which was the example that I used to get my wasm_bindgen client working correctly for the first time.

Yeah so about miniquad.. It is a project that I believe is sorely needed in the Rust gamedev ecosystem right now. I made a simple C++ game engine based on https://github.com/floooh/sokol a couple years ago, which is a lower-level graphics API with a focus on cross-platform compilation. I'm a believer in the motivations, design, architecture, & API of sokol, and as far as I can tell, Fedor did a very good job bringing the same methodology to miniquad.

At this point in the Rust gamedev ecosystem, miniquad is currently the best solution we have for a widely cross-platform lower level graphics API, and it has other quality of life cross-platform implementations for sound, input, and asset loading too which is all you need to get a simple game off the ground.

Now that being said, it's my opinion that miniquad is only hurting itself and it's usefulness by not embracing wasm_bindgen like the rest of the Rust community seems to be doing. The community's argument is that wasm_bindgen can increase code compilation times, result in larger Wasm file sizes, and that Javascript/Rust interop code can be slightly less performant. I've seen some of these differences myself while playing around with miniquad/wasm_bindgen. So there is a tradeoff between those results and the ease-of-use & interoperability of wasm_bindgen.

It is my opinion that perhaps the miniquad API should have at least TWO separate backend implementations of it's Wasm compilation target - perhaps selected by a feature flag. They can keep their current custom JS interop implementation, and have a separate wasm_bindgen backend that plays well with other wasm_bindgen packages.

Anyway, I invite you to check out their community & Discord, I also think it's a great community and there is some good activity happening there.

Thanks again for this PR!

**Comment by smokku** [comment]
With a bit of hackery you can use miniquad with wasm_bindgen code.
https://github.com/smokku/gwg-bindgen

**Pull request merged**
